### ISSUE TITLE
    ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by mgaulton** [pe3zx/mthc#10]
Currently running into this error and not sure why. Requirements.txt have been installed etc. Running on Opensuse Tumbleweed 

Collecting oauth2==1.9.0.post1 (from -r REQUIREMENTS (line 53))
  Downloading https://files.pythonhosted.org/packages/a0/6f/86db603912ecd04109af952c38bc08928886cf0e34c723481fa7db98b4b5/oauth2-1.9.0.post1-py2.py3-none-any.whl
Collecting opencv-python==4.4.0.44 (from -r REQUIREMENTS (line 54))
  Downloading https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1m_bh6g1/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1m_bh6g1/opencv-python/
ERROR: Service 'misp-web' failed to build: The command '/bin/sh -c cd misp-modules &&     pip3 install -I -r REQUIREMENTS &&     pip3 install -I . &&     echo "sudo -u www-data misp-modules -s -l 127.0.0.1 &" >>/etc/rc.local' returned a non-zero code: 1

**Comment by pe3zx** [comment]
Hi @mgaulton,

The issue is confirmed. I haven't tried this yet but there's [possible workaround here](https://github.com/openvinotoolkit/dlstreamer_gst/issues/105).

I will test the workaround and update pe3zx/misp-docker again if it works.

**Comment by mgaulton** [comment]
Awesome, thanks.

**Comment by pe3zx** [comment]
Add pe3zx/misp-docker@a53ae690e3cd1cbb6c66bd7ed09186e647e7f2db to upgrade pip before installing any packages. Testing found any problems.

Could you pull the recent changes and give it a try?

**Comment by mgaulton** [comment]
Trying this now.
