### ISSUE TITLE
Cortex requirements

### ISSUE THREAD

**Issue by mgaulton** [pe3zx/mthc#11]
I'm looking for a clarification.
I initially ran the below on my host, as it didn't refer to running it inside a docker.
How should this actually be run?
before/after the docker-compose up?
which docker / host?

for I in $(find Cortex-Analyzers -name 'requirements.txt'); do pip2 install -r $I; done && \
for I in $(find Cortex-Analyzers -name 'requirements.txt'); do pip3 install -r $I || true; done

**Comment by pe3zx** [comment]
Hi @mgaulton,

Thanks for pointing out. The commands must be run on the Cortex container on the path `Cortex-Analyzers` is mounted to. The instruction on Wiki has been updated accordingly.
