### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.util'

### ISSUE THREAD

**Issue by jtp2112** [pe3zx/mthc#13]
During docker-compose up -d:

Collecting importlib==1.0.4
  Downloading importlib-1.0.4.zip (7.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qy0u37e9/importlib_c166265216f74de7b3fade999d0b8c1f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qy0u37e9/importlib_c166265216f74de7b3fade999d0b8c1f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z_sy139j
         cwd: /tmp/pip-install-qy0u37e9/importlib_c166265216f74de7b3fade999d0b8c1f/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 10, in <module>
        import distutils.core
      File "/usr/lib/python3.6/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib/python3.6/distutils/dist.py", line 19, in <module>
        from distutils.util import check_environ, strtobool, rfc822_escape
      File "/usr/lib/python3.6/distutils/util.py", line 9, in <module>
        import importlib.util
    ModuleNotFoundError: No module named 'importlib.util'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'misp-web' failed to build: The command '/bin/sh -c cd misp-modules &&     pip3 install -I -r REQUIREMENTS &&     pip3 install -I . &&     echo "sudo -u www-data misp-modules -s -l 127.0.0.1 &" >>/etc/rc.local' returned a non-zero code: 1

**Comment by pe3zx** [comment]
Confirm issue based on [scheduled Actions flow #7](https://github.com/pe3zx/mthc/actions/runs/392758183)

**Comment by pe3zx** [comment]
The issue is identified during [MISP modules installing process](https://github.com/pe3zx/misp-docker/blob/master/web/Dockerfile#L143) where `misp-modules` setup its dependencies. The same issue has also been reported to the upstream as MISP/misp-modules#453.

I will follow any change made to resolve MISP/misp-modules#453 and merge to the project. In case you really need to spin up the platform, I suggest comment out the *Install MISP modules* section on [`Dockerfile`](https://github.com/pe3zx/misp-docker/blob/master/web/Dockerfile) and rebuilding it.

**Comment by pe3zx** [comment]
Added workaround by forcing `misp-modules` to be installed from stable version.

**Comment by pe3zx** [comment]
Workaround confirmed with [Actions flow #8](https://github.com/pe3zx/mthc/actions/runs/406497626).
