### ISSUE TITLE
error python - deploy

### ISSUE THREAD

**Issue by robben-ar** [pe3zx/mthc#2]
I am having trouble deploying the docker-compose.yml
Do you know if there are conflicts with python versions?

![image](https://user-images.githubusercontent.com/16881807/64073489-08a85400-cc75-11e9-8f4c-5f57c10fda6b.png)

Regards.-

**Comment by pe3zx** [comment]
Hi @robben-ar, sorry for late reply.

According to error on the image, this happens because `libxml2` and/or `libxslt` is missing and leads to python module `lxml` compliation error. Please make sure that both libs are already installed.

Best regards.

**Comment by pe3zx** [comment]
This issue has been closed because there has been no response
