### ISSUE TITLE
Hadd to add python-dateutil in misp-web dockerfile

### ISSUE THREAD

**Issue by icepaule** [pe3zx/mthc#3]
Hello,
just to keep you up to date, I had to add another apt package to be installed.

The iroginal error:
**error: The 'python-dateutil' distribution was not found and is required by cybox**
ERROR: Service 'misp-web' failed to build: The command '/bin/sh -c python setup.py install' returned a non-zero code: 1

I've added **python-dateutil** into the Dockerfile at ** ./mthc/apps/misp-docker/web**

RUN apt-get install -y **python-dateutil** python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev python-setuptools libfuzzy-dev
RUN apt-get install -y cron logrotate supervisor syslog-ng-core
RUN apt-get clean

After making this change, the "build" installation went through smoothly.  :-)

Thanks a lot for all the great work you did.

Cheers
Marcus

**Comment by pe3zx** [comment]
Hi @icepaule,

I've just merged the misp/misp-docker to pe3zx/misp-docker which mthc is relying on. 
Could you help me verify that this issue still present?

Thank you very much!

**Comment by pe3zx** [comment]
Closing due to no further response.
