### ISSUE TITLE
ERROR: Service 'misp-web' failed to build

### ISSUE THREAD

**Issue by joker2013** [pe3zx/mthc#5]
Step 52/144 : RUN php composer-setup.php
 ---> Running in dc96c2a77f56
Could not open input file: composer-setup.php
ERROR: Service 'misp-web' failed to build: The command '/bin/sh -c php composer-setup.php' returned a non-zero code: 1

**Comment by joker2013** [comment]
It is an issue with the composer-setup.php file change and the resulting SHA384 hash. Check https://getcomposer.org/download/ for the new hash.

https://github.com/MISP/misp-docker/issues/64

**Comment by joker2013** [comment]
https://github.com/MISP/MISP/pull/5473

**Comment by joker2013** [comment]
# FIX COMPOSER
RUN curl --fail --location -o composer-setup.php https://getcomposer.org/installer && \
    EXPECTED_SIGNATURE="$(curl https://composer.github.io/installer.sig)"; php -r "if (hash_file('sha384', 'composer-setup.php') == '$(echo $EXPECTED_SIGNATURE)' ) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');"
# END FIX

**Comment by joker2013** [comment]
misp-docker/web/Dockerfile

**Comment by leips** [comment]
Edit the misp dockerfile and add the last hash of Composer

`
# FIX COMPOSER
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
# END FIX`

**Comment by pe3zx** [comment]
Hi, I've just updated the submodules. Could you try it again?

**Comment by pe3zx** [comment]
Closing due to no further response.
